import { z } from "zod";
import { defineTool } from "./base.js";
import { createIssues, isGithubConfigured, parseRepo } from "../../services/github.js";
import { getDb, isDbConfigured } from "../../db/client.js";
import { tasks as tasksTable } from "../../db/schema.js";
import { eq } from "drizzle-orm";
import { recordAudit } from "../../db/repo.js";
import { ConfigError, ValidationError } from "../../utils/errors.js";
import { handoffAgent } from "../agents/handoff.agent.js";

const taskInput = z.object({
  title: z.string(),
  description: z.string().default(""),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  acceptanceCriteria: z.array(z.string()).optional(),
  labels: z.array(z.string()).optional(),
});

const inputSchema = {
  repo: z.string().describe('Target GitHub repository as "owner/repo" or URL.'),
  projectId: z.string().optional().describe("If set, pull persisted tasks for this project."),
  tasks: z.array(taskInput).optional().describe("Explicit tasks to create issues from."),
};

function issueBody(t: z.infer<typeof taskInput>): string {
  const ac = (t.acceptanceCriteria ?? []).map((c) => `- [ ] ${c}`).join("\n");
  return [
    t.description,
    t.priority ? `\n**Priority:** ${t.priority}` : "",
    ac ? `\n\n### Acceptance Criteria\n${ac}` : "",
    "\n\n_Generated by Devibe._",
  ].join("");
}

export const createGithubIssues = defineTool({
  name: "create_github_issues",
  title: "Create GitHub Issues",
  description: "Create GitHub issues from generated or persisted tasks.",
  inputSchema,
  async handler(args, ctx) {
    if (!isGithubConfigured()) {
      throw new ConfigError("GITHUB_TOKEN is not configured. Set it to create issues.");
    }
    const { owner, repo } = parseRepo(args.repo);

    let source = args.tasks ?? [];
    if ((!source || source.length === 0) && args.projectId && isDbConfigured()) {
      const rows = await getDb().select().from(tasksTable).where(eq(tasksTable.projectId, args.projectId));
      source = rows.map((r) => ({
        title: r.title,
        description: r.description,
        priority: r.priority,
        acceptanceCriteria: r.acceptanceCriteria,
        labels: [`priority:${r.priority}`],
      }));
    }

    if (!source || source.length === 0) {
      throw new ValidationError("No tasks provided and none found for the project.");
    }

    const created = await createIssues(
      owner,
      repo,
      source.map((t) => ({
        title: t.title,
        body: issueBody(t),
        labels: t.labels ?? (t.priority ? [`priority:${t.priority}`] : undefined),
      })),
    );

    await recordAudit({
      actorId: ctx.actorId,
      action: "create_github_issues",
      resourceType: "project",
      resourceId: args.projectId ?? null,
      metadata: { repo: `${owner}/${repo}`, count: created.length },
    });

    return { repo: `${owner}/${repo}`, issues: created, agent: handoffAgent.role };
  },
});
